import { SaleItem, PurchaseItem, ExpenseItem } from './types';

export const INITIAL_PRODUCTS: string[] = [
  'SHAFT KIKI',
  'CLUTCH WIRE',
  'CHAIN BOX',
  'OIL SEAL',
  'BEARING',
  'HANDLE SWITH',
  'CRANKSHAFT',
  'CHAIN SINGLE',
  'GASKET SINGLE',
  'BRAKE PAD',
  'GEARBOX',
  'PISTON KIT',
  'SPOKET SET',
  'BRAKE SHOE',
  'BATTERY',
  'MASTER CYLINDER',
  'CLUTCH CABLE',
  'ACCELERATOR CABLE',
  'HEADLIGHT',
  'RING PISTON',
  'SPEED METER CABLE',
  'KICK STARTER'
];

export const INITIAL_BRANDS: string[] = [
  'BOXER',
  'TVS',
  'SINORAY',
  'HUNTER',
  'SANLG',
  'HAOJUE',
  'SANMOTO',
  'KINGLION',
  'WANHOO',
  'PIAGGIO',
  'FEKON'
];

export const INITIAL_MOTORCYCLE_TYPES: string[] = [
  'BODABODA',
  'BAJAJI',
  'GUTA',
  'QUADBIKE',
  'ELECTRIC BICYCLE',
  'SCOOTER',
  'OTHER'
];

export const INITIAL_SALES: SaleItem[] = [
  {
    id: 's-1',
    date: '16/04/2025',
    typeOfMotorcycle: 'BAJAJI',
    energyMode: 'CNG',
    brief: '',
    brand: 'TVS',
    productName: 'CLUTCH WIRE',
    quantity: 10,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 12000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 120000
  },
  {
    id: 's-2',
    date: '15/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'SHAFT KIKI',
    quantity: 10,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'Old',
    pricePerUnit: 12000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 120000
  },
  {
    id: 's-3',
    date: '14/04/2025',
    typeOfMotorcycle: 'BAJAJI',
    energyMode: 'PETROL',
    brief: '',
    brand: 'PIAGGIO',
    productName: 'KICK STARTER',
    quantity: 9,
    sparePartCompany: '',
    location: 'Outside Region',
    customer: 'New',
    pricePerUnit: 8000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 72000
  },
  {
    id: 's-4',
    date: '13/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'HEADLIGHT',
    quantity: 9,
    sparePartCompany: '',
    location: 'Outside Region',
    customer: 'New',
    pricePerUnit: 25000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 225000
  },
  {
    id: 's-5',
    date: '12/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'RING PISTON',
    quantity: 8,
    sparePartCompany: '',
    location: 'Outside Region',
    customer: 'Old',
    pricePerUnit: 10000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 80000
  },
  {
    id: 's-6',
    date: '11/04/2025',
    typeOfMotorcycle: 'BAJAJI',
    energyMode: 'ELECTRIC',
    brief: '',
    brand: 'TVS',
    productName: 'BATTERY',
    quantity: 2,
    sparePartCompany: '',
    location: 'Outside Region',
    customer: 'Old',
    pricePerUnit: 35000,
    service: 'No',
    servicePrice: 0,
    totalAmount: 70000
  },
  {
    id: 's-7',
    date: '10/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'SPEED METER CABLE',
    quantity: 8,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'Old',
    pricePerUnit: 15000,
    service: 'Yes',
    servicePrice: 25000,
    totalAmount: 145000
  },
  {
    id: 's-8',
    date: '09/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'TVS',
    productName: 'MASTER CYLINDER',
    quantity: 8,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 7000,
    service: 'Yes',
    servicePrice: 20000,
    totalAmount: 76000
  },
  {
    id: 's-9',
    date: '08/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'TVS',
    productName: 'BRAKE SHOE',
    quantity: 8,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 8000,
    service: 'Yes',
    servicePrice: 20000,
    totalAmount: 84000
  },
  {
    id: 's-10',
    date: '07/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'CRANKSHAFT',
    quantity: 3,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 8000,
    service: 'Yes',
    servicePrice: 20000,
    totalAmount: 44000
  },
  {
    id: 's-11',
    date: '06/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'HANDLE SWITH',
    quantity: 3,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 9000,
    service: 'Yes',
    servicePrice: 15000,
    totalAmount: 42000
  },
  {
    id: 's-12',
    date: '05/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'BRAKE PAD',
    quantity: 4,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 7000,
    service: 'Yes',
    servicePrice: 10000,
    totalAmount: 38000
  },
  {
    id: 's-13',
    date: '04/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'CNG',
    brief: '',
    brand: 'SINORAY',
    productName: 'SHAFT KIKI',
    quantity: 5,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 10000,
    service: 'Yes',
    servicePrice: 15000,
    totalAmount: 65000
  },
  {
    id: 's-14',
    date: '04/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'CNG',
    brief: '',
    brand: 'TVS',
    productName: 'CLUTCH WIRE',
    quantity: 2,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 12000,
    service: 'Yes',
    servicePrice: 10000,
    totalAmount: 34000
  },
  {
    id: 's-15',
    date: '03/04/2025',
    typeOfMotorcycle: 'BODABODA',
    energyMode: 'PETROL',
    brief: '',
    brand: 'BOXER',
    productName: 'OIL SEAL',
    quantity: 5,
    sparePartCompany: '',
    location: 'Within Region',
    customer: 'New',
    pricePerUnit: 9000,
    service: 'Yes',
    servicePrice: 20000,
    totalAmount: 65000
  }
];

export const INITIAL_PURCHASES: PurchaseItem[] = [
  {
    id: 'p-1',
    date: '01/04/2025',
    productName: 'KICK STARTER',
    typeOfMotorcycle: 'BAJAJI',
    brand: 'PIAGGIO',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 2000,
    paymentMode: 'Cash',
    account: 'CASH',
    description: '',
    totalCost: 20000
  },
  {
    id: 'p-2',
    date: '01/04/2025',
    productName: 'HEADLIGHT',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 10000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 100000
  },
  {
    id: 'p-3',
    date: '01/04/2025',
    productName: 'RING PISTON',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 4000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 40000
  },
  {
    id: 'p-4',
    date: '01/04/2025',
    productName: 'BATTERY',
    typeOfMotorcycle: 'BAJAJI',
    brand: 'TVS',
    quantity: 5,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 25000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 125000
  },
  {
    id: 'p-5',
    date: '01/04/2025',
    productName: 'SPEED METER CABLE',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 8000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 80000
  },
  {
    id: 'p-6',
    date: '01/04/2025',
    productName: 'MASTER CYLINDER',
    typeOfMotorcycle: 'BODABODA',
    brand: 'TVS',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 6000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 60000
  },
  {
    id: 'p-7',
    date: '01/04/2025',
    productName: 'BRAKE SHOE',
    typeOfMotorcycle: 'BODABODA',
    brand: 'TVS',
    quantity: 10,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 3000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 30000
  },
  {
    id: 'p-8',
    date: '01/04/2025',
    productName: 'CRANKSHAFT',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 5,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 5000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 25000
  },
  {
    id: 'p-9',
    date: '01/04/2025',
    productName: 'HANDLE SWITH',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 5,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 4000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 20000
  },
  {
    id: 'p-10',
    date: '01/04/2025',
    productName: 'BRAKE PAD',
    typeOfMotorcycle: 'BODABODA',
    brand: 'BOXER',
    quantity: 8,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 2000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 16000
  },
  {
    id: 'p-11',
    date: '01/04/2025',
    productName: 'OIL SEAL',
    typeOfMotorcycle: 'BAJAJI',
    brand: 'TVS',
    quantity: 15,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 6000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 90000
  },
  {
    id: 'p-12',
    date: '01/04/2025',
    productName: 'CLUTCH WIRE',
    typeOfMotorcycle: 'BAJAJI',
    brand: 'TVS',
    quantity: 20,
    source: 'Physical',
    supplierName: 'JJ',
    sparePartCompany: '',
    costPerUnit: 7000,
    paymentMode: 'emoney',
    account: 'CRDB',
    description: '',
    totalCost: 140000
  },
  {
    id: 'p-13',
    date: '01/04/2025',
    productName: 'SHAFT KIKI',
    typeOfMotorcycle: 'BODABODA',
    brand: 'SINORAY',
    quantity: 30,
    source: 'Physical',
    supplierName: 'Wuhan LTD',
    sparePartCompany: '',
    costPerUnit: 5000,
    paymentMode: 'emoney',
    account: 'VODA CARD',
    description: 'Ship charges included',
    totalCost: 150000
  }
];

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: 'e-1',
    date: '07/04/2025',
    expenseType: 'Training',
    brief: 'Staff training workshop',
    recurring: 'No',
    period: 'None',
    totalCost: 50000,
    paymentMode: 'Cash',
    account: 'CASH',
    description: 'Training costs',
    total: 50000
  },
  {
    id: 'e-2',
    date: '05/04/2025',
    expenseType: 'Waste collection',
    brief: 'Sanitation weekly fee',
    recurring: 'Yes',
    period: 'Weekly',
    totalCost: 25000,
    paymentMode: 'Cash',
    account: 'CASH',
    description: 'Weekly waste disposal',
    total: 25000
  }
];

export const INITIAL_CONTACT = {
  businessName: 'SM TEMPLATE T3 - SPEA ZA PIKIPIKI SPARE PARTS',
  ownerName: 'Rashid Mahadhi',
  phone: '+255 700 000 000',
  email: 'rashidmahadhi617@gmail.com',
  address: 'Kariakoo / Dar es Salaam, Tanzania',
  currency: 'TZS',
  systemVersion: 'SM Template Version 3.0',
  notes: 'Mfumo huu unajumuisha jedwali la Bidhaa (Products), Mauzo (Sales), Manunuzi (Purchases), Matumizi (Expenses), Ufuatiliaji wa Stoo (Stock Tracker), Dashibodi ya Biashara (Dashboard), na Ripoti.'
};
